### ISSUE TITLE
Configuration issue with ROS2-driver

### ISSUE THREAD

**Issue by joh11990** [SCHUNK-GmbH-Co-KG/schunk_svh_ros_driver#12]
I am currently trying to get the Schunk SVH ROS Driver up and running.
I was able to get the ROS1 driver up and running without major problems and move the hand, which leads me to believe that the wiring is correct.
However, I have not yet been able to get the ROS2 driver up and running. Downloading and building worked, but the subsequent communication with the hand did not.
I don't think the driver itself is the problem, but maybe the configuration?
[ROS2.log](https://github.com/user-attachments/files/16096283/ROS2.log)
[ROS1.log](https://github.com/user-attachments/files/16096284/ROS1.log)

**Comment by stefanscherzinger** [comment]
Hi @joh11990 

Thanks for using the SVH!
Your `ROS2.log` file seems normal. At least I don't recognize something suspicious on first sight.

Could you post the outputs of `ros2 node list` and `ros2 topic list` directly here in the chat? I'm wondering if the driver is up and running as expected.

**Comment by joh11990** [comment]
![Screenshot from 2024-07-04 14-09-07](https://github.com/SCHUNK-SE-Co-KG/schunk_svh_ros_driver/assets/174697795/682d9d52-eaa8-433e-821b-0ef257fb942f)

**Comment by stefanscherzinger** [comment]
Hm, this looks normal. Are you getting values from the hand via the `/joint_states` topic?
```bash
ros2 topic echo /joint_states
```
Please copy and paste some of the output. Don't paste images, because their text can't be searched and copied/quoted.

**Comment by joh11990** [comment]
header:
  stamp:
    sec: 1720705302
    nanosec: 691423637
  frame_id: ''
name:
- Left_Hand_Index_Finger_Distal
- Left_Hand_Thumb_Flexion
- Left_Hand_Middle_Finger_Distal
- Left_Hand_Thumb_Opposition
- Left_Hand_Ring_Finger
- Left_Hand_Middle_Finger_Proximal
- Left_Hand_Pinky
- Left_Hand_Index_Finger_Proximal
- Left_Hand_Finger_Spread
position:
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
velocity:
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
effort:
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
---
header:
  stamp:
    sec: 1720705302
    nanosec: 699402283
  frame_id: ''
name:
- Left_Hand_Index_Finger_Distal
- Left_Hand_Thumb_Flexion
- Left_Hand_Middle_Finger_Distal
- Left_Hand_Thumb_Opposition
- Left_Hand_Ring_Finger
- Left_Hand_Middle_Finger_Proximal
- Left_Hand_Pinky
- Left_Hand_Index_Finger_Proximal
- Left_Hand_Finger_Spread
position:
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
velocity:
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
effort:
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
---
header:
  stamp:
    sec: 1720705302
    nanosec: 707425137
  frame_id: ''
name:
- Left_Hand_Index_Finger_Distal
- Left_Hand_Thumb_Flexion
- Left_Hand_Middle_Finger_Distal
- Left_Hand_Thumb_Opposition
- Left_Hand_Ring_Finger
- Left_Hand_Middle_Finger_Proximal
- Left_Hand_Pinky
- Left_Hand_Index_Finger_Proximal
- Left_Hand_Finger_Spread
position:
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
velocity:
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
effort:
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan
- .nan

**Comment by stefanscherzinger** [comment]
@joh11990 
As we just discussed in the call, I think it might be something on the system level involving _read_ and _write_ to the `/dev/ttyUSB0` device. Unfortunately, as I mentioned, I cannot reproduce this here with real hardware.
Please feel free to share any further insights you might get.

**Comment by stefanscherzinger** [comment]
@joh11990 
I was just thinking, maybe the driver outputs useful _debug_ information when decreasing the default logger level. I would quickly change [this line](https://github.com/SCHUNK-SE-Co-KG/schunk_svh_ros_driver/blob/e35bebf9e2137a11f2677e6e0f54f66a03348afb/schunk_svh_driver/include/schunk_svh_driver/ROSLogHandler.hpp#L51) to something like

```cpp
void setupROSLogHandler(LogLevel level = LogLevel::DEBUG);
```
and recompile. This driver will spam a lot, but maybe there's useful information about the failing serial connection.

When posting output here, try to make use of Github's _markdown_ support.
For instance, copy log output from the terminal and post it between three backticks:
<pre>
```bash
several lines of output ..
```
</pre>
This will render the output in a code box like this
```bash
several lines of output ..
```

**Comment by stefanscherzinger** [comment]
@joh11990 

Any updates on this topic?

**Comment by joh11990** [comment]
We've resolved the issue with the hand. The problem wasn't with the ROS1 or ROS2 driver but rather a combination of hardware factors. Specifically, using a ground isolator on the workstation (ROS2) helped, but it caused issues with the laptop (ROS1). After adding the isolator and resetting the hand's power, communication worked as expected.
